//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEuler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectEuler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pogonias
        ///universe
        ///abstractnesses
        ///outfaced
        ///touse
        ///quaysides
        ///underbudded
        ///obtunded
        ///undervaluing
        ///schavs
        ///waxwing
        ///tumidily
        ///obesities
        ///tref
        ///approximates
        ///whydahs
        ///romaine
        ///refastening
        ///sanies
        ///sneesh
        ///ribes
        ///scatbacks
        ///talent
        ///revoices
        ///unreeler
        ///preset
        ///spiced
        ///slangy
        ///rehearser
        ///melinite
        ///misliker
        ///rarebits
        ///dockages
        ///sights
        ///rockabies
        ///wreathy
        ///treadle
        ///ululates
        ///plenteous
        ///sublease
        ///douche
        ///wriggly
        ///marvelled
        ///waspy
        ///superpatriotisms
        ///nursery
        ///pastiches
        ///necrosing
        ///stature
        ///sambhurs
        ///floodlit
        ///swis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 73167176531330624919225119674426574742355349194934
        ///96983520312774506326239578318016984801869478851843
        ///85861560789112949495459501737958331952853208805511
        ///12540698747158523863050715693290963295227443043557
        ///66896648950445244523161731856403098711121722383113
        ///62229893423380308135336276614282806444486645238749
        ///30358907296290491560440772390713810515859307960866
        ///70172427121883998797908792274921901699720888093776
        ///65727333001053367881220235421809751254540594752243
        ///52584907711670556013604839586446706324415722 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Problem008Data {
            get {
                return ResourceManager.GetString("Problem008Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
        ///49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
        ///81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
        ///52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
        ///22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
        ///24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
        ///32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
        ///67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
        ///24 55 58 05 66 73 99 26  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Problem011Data {
            get {
                return ResourceManager.GetString("Problem011Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 37107287533902102798797998220837590246510135740250
        ///46376937677490009712648124896970078050417018260538
        ///74324986199524741059474233309513058123726617309629
        ///91942213363574161572522430563301811072406154908250
        ///23067588207539346171171980310421047513778063246676
        ///89261670696623633820136378418383684178734361726757
        ///28112879812849979408065481931592621691275889832738
        ///44274228917432520321923589422876796487670272189318
        ///47451445736001306439091167216856844588711603153276
        ///70386486105843025439939619828917593665686757 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Problem013Data {
            get {
                return ResourceManager.GetString("Problem013Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75
        ///95 64
        ///17 47 82
        ///18 35 87 10
        ///20 04 82 47 65
        ///19 01 23 75 03 34
        ///88 02 77 73 07 63 67
        ///99 65 04 28 06 16 70 92
        ///41 41 26 56 83 40 80 70 33
        ///41 48 72 33 47 32 37 16 94 29
        ///53 71 44 65 25 43 91 52 97 51 14
        ///70 11 33 28 77 73 17 78 39 68 17 57
        ///91 71 52 38 17 14 91 43 58 50 27 29 48
        ///63 66 04 68 89 53 67 30 73 16 69 87 40 31
        ///04 62 98 27 23 09 70 98 73 93 38 53 60 04 23.
        /// </summary>
        internal static string Problem018Data {
            get {
                return ResourceManager.GetString("Problem018Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;MARY&quot;,&quot;PATRICIA&quot;,&quot;LINDA&quot;,&quot;BARBARA&quot;,&quot;ELIZABETH&quot;,&quot;JENNIFER&quot;,&quot;MARIA&quot;,&quot;SUSAN&quot;,&quot;MARGARET&quot;,&quot;DOROTHY&quot;,&quot;LISA&quot;,&quot;NANCY&quot;,&quot;KAREN&quot;,&quot;BETTY&quot;,&quot;HELEN&quot;,&quot;SANDRA&quot;,&quot;DONNA&quot;,&quot;CAROL&quot;,&quot;RUTH&quot;,&quot;SHARON&quot;,&quot;MICHELLE&quot;,&quot;LAURA&quot;,&quot;SARAH&quot;,&quot;KIMBERLY&quot;,&quot;DEBORAH&quot;,&quot;JESSICA&quot;,&quot;SHIRLEY&quot;,&quot;CYNTHIA&quot;,&quot;ANGELA&quot;,&quot;MELISSA&quot;,&quot;BRENDA&quot;,&quot;AMY&quot;,&quot;ANNA&quot;,&quot;REBECCA&quot;,&quot;VIRGINIA&quot;,&quot;KATHLEEN&quot;,&quot;PAMELA&quot;,&quot;MARTHA&quot;,&quot;DEBRA&quot;,&quot;AMANDA&quot;,&quot;STEPHANIE&quot;,&quot;CAROLYN&quot;,&quot;CHRISTINE&quot;,&quot;MARIE&quot;,&quot;JANET&quot;,&quot;CATHERINE&quot;,&quot;FRANCES&quot;,&quot;ANN&quot;,&quot;JOYCE&quot;,&quot;DIANE&quot;,&quot;ALICE&quot;,&quot;JULIE&quot;,&quot;HEATHER&quot;,&quot;TER....
        /// </summary>
        internal static string Problem022Data {
            get {
                return ResourceManager.GetString("Problem022Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;A&quot;,&quot;ABILITY&quot;,&quot;ABLE&quot;,&quot;ABOUT&quot;,&quot;ABOVE&quot;,&quot;ABSENCE&quot;,&quot;ABSOLUTELY&quot;,&quot;ACADEMIC&quot;,&quot;ACCEPT&quot;,&quot;ACCESS&quot;,&quot;ACCIDENT&quot;,&quot;ACCOMPANY&quot;,&quot;ACCORDING&quot;,&quot;ACCOUNT&quot;,&quot;ACHIEVE&quot;,&quot;ACHIEVEMENT&quot;,&quot;ACID&quot;,&quot;ACQUIRE&quot;,&quot;ACROSS&quot;,&quot;ACT&quot;,&quot;ACTION&quot;,&quot;ACTIVE&quot;,&quot;ACTIVITY&quot;,&quot;ACTUAL&quot;,&quot;ACTUALLY&quot;,&quot;ADD&quot;,&quot;ADDITION&quot;,&quot;ADDITIONAL&quot;,&quot;ADDRESS&quot;,&quot;ADMINISTRATION&quot;,&quot;ADMIT&quot;,&quot;ADOPT&quot;,&quot;ADULT&quot;,&quot;ADVANCE&quot;,&quot;ADVANTAGE&quot;,&quot;ADVICE&quot;,&quot;ADVISE&quot;,&quot;AFFAIR&quot;,&quot;AFFECT&quot;,&quot;AFFORD&quot;,&quot;AFRAID&quot;,&quot;AFTER&quot;,&quot;AFTERNOON&quot;,&quot;AFTERWARDS&quot;,&quot;AGAIN&quot;,&quot;AGAINST&quot;,&quot;AGE&quot;,&quot;AGENCY&quot;,&quot;AGENT&quot;,&quot;AGO&quot;,&quot;AGREE&quot;,&quot;AGREEMENT&quot;,&quot....
        /// </summary>
        internal static string Problem042Data {
            get {
                return ResourceManager.GetString("Problem042Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8C TS KC 9H 4S 7D 2S 5D 3S AC
        ///5C AD 5D AC 9C 7C 5H 8D TD KS
        ///3H 7H 6S KC JS QH TD JC 2D 8S
        ///TH 8H 5C QS TC 9H 4D JC KS JS
        ///7C 5H KC QH JD AS KH 4C AD 4S
        ///5H KS 9C 7D 9H 8D 3S 5D 5C AH
        ///6H 4H 5C 3H 2H 3S QH 5S 6S AS
        ///TD 8C 4H 7C TC KC 4C 3H 7S KS
        ///7C 9C 6D KD 3H 4C QS QC AC KH
        ///JC 6S 5H 2H 2D KD 9D 7C AS JS
        ///AD QH TH 9D 8H TS 6D 3S AS AC
        ///2H 4S 5C 5S TC KC JD 6C TS 3C
        ///QD AS 6H JS 2C 3D 9H KC 4H 8S
        ///KD 8S 9S 7C 2S 3S 6D 6S 4H KC
        ///3C 8C 2D 7D 4D 9S 4S QH 4H JD
        ///8C KC 7S TC 2D TS 8H QD AC 5C
        ///3D KH QD 6C 6S A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Problem054Data {
            get {
                return ResourceManager.GetString("Problem054Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 79,59,12,2,79,35,8,28,20,2,3,68,8,9,68,45,0,12,9,67,68,4,7,5,23,27,1,21,79,85,78,79,85,71,38,10,71,27,12,2,79,6,2,8,13,9,1,13,9,8,68,19,7,1,71,56,11,21,11,68,6,3,22,2,14,0,30,79,1,31,6,23,19,10,0,73,79,44,2,79,19,6,28,68,16,6,16,15,79,35,8,11,72,71,14,10,3,79,12,2,79,19,6,28,68,32,0,0,73,79,86,71,39,1,71,24,5,20,79,13,9,79,16,15,10,68,5,10,3,14,1,10,14,1,3,71,24,13,19,7,68,32,0,0,73,79,87,71,39,1,71,12,22,2,14,16,2,11,68,2,25,1,21,22,16,15,6,10,0,79,16,15,10,22,2,79,13,20,65,68,41,0,16,15,6,10,0,79,1,31,6,2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Problem059Data {
            get {
                return ResourceManager.GetString("Problem059Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 59
        ///73 41
        ///52 40 09
        ///26 53 06 34
        ///10 51 87 86 81
        ///61 95 66 57 25 68
        ///90 81 80 38 92 67 73
        ///30 28 51 76 81 18 75 44
        ///84 14 95 87 62 81 17 78 58
        ///21 46 71 58 02 79 62 39 31 09
        ///56 34 35 53 78 31 81 18 90 93 15
        ///78 53 04 21 84 93 32 13 97 11 37 51
        ///45 03 81 79 05 18 78 86 13 30 63 99 95
        ///39 87 96 28 03 38 42 17 82 87 58 07 22 57
        ///06 17 51 17 07 93 09 07 75 97 95 78 87 08 53
        ///67 66 59 60 88 99 94 65 55 77 55 34 27 53 78 28
        ///76 40 41 04 87 16 09 42 75 69 23 97 30 60 10 79 87
        ///12 10 44 26 21 36 32 84 98 60 13 12  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Problem067Data {
            get {
                return ResourceManager.GetString("Problem067Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 319
        ///680
        ///180
        ///690
        ///129
        ///620
        ///762
        ///689
        ///762
        ///318
        ///368
        ///710
        ///720
        ///710
        ///629
        ///168
        ///160
        ///689
        ///716
        ///731
        ///736
        ///729
        ///316
        ///729
        ///729
        ///710
        ///769
        ///290
        ///719
        ///680
        ///318
        ///389
        ///162
        ///289
        ///162
        ///718
        ///729
        ///319
        ///790
        ///680
        ///890
        ///362
        ///319
        ///760
        ///316
        ///729
        ///380
        ///319
        ///728
        ///716.
        /// </summary>
        internal static string Problem079Data {
            get {
                return ResourceManager.GetString("Problem079Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4445,2697,5115,718,2209,2212,654,4348,3079,6821,7668,3276,8874,4190,3785,2752,9473,7817,9137,496,7338,3434,7152,4355,4552,7917,7827,2460,2350,691,3514,5880,3145,7633,7199,3783,5066,7487,3285,1084,8985,760,872,8609,8051,1134,9536,5750,9716,9371,7619,5617,275,9721,2997,2698,1887,8825,6372,3014,2113,7122,7050,6775,5948,2758,1219,3539,348,7989,2735,9862,1263,8089,6401,9462,3168,2758,3748,5870
        ///1096,20,1318,7586,5167,2642,1443,5741,7621,7030,5526,4244,2348,4641,9827,2448,6918,5883,3737,300,7116,6531,567,5997,397 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Problem081Data {
            get {
                return ResourceManager.GetString("Problem081Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMMMDCLXXII
        ///MMDCCCLXXXIII
        ///MMMDLXVIIII
        ///MMMMDXCV
        ///DCCCLXXII
        ///MMCCCVI
        ///MMMCDLXXXVII
        ///MMMMCCXXI
        ///MMMCCXX
        ///MMMMDCCCLXXIII
        ///MMMCCXXXVII
        ///MMCCCLXXXXIX
        ///MDCCCXXIIII
        ///MMCXCVI
        ///CCXCVIII
        ///MMMCCCXXXII
        ///MDCCXXX
        ///MMMDCCCL
        ///MMMMCCLXXXVI
        ///MMDCCCXCVI
        ///MMMDCII
        ///MMMCCXII
        ///MMMMDCCCCI
        ///MMDCCCXCII
        ///MDCXX
        ///CMLXXXVII
        ///MMMXXI
        ///MMMMCCCXIV
        ///MLXXII
        ///MCCLXXVIIII
        ///MMMMCCXXXXI
        ///MMDCCCLXXII
        ///MMMMXXXI
        ///MMMDCCLXXX
        ///MMDCCCLXXIX
        ///MMMMLXXXV
        ///MCXXI
        ///MDCCCXXXVII
        ///MMCCCLXVII
        ///MCDXXXV
        ///CCXXXIII
        ///CMXX
        ///MMMCLXIV
        ///MCCCLXXXVI
        ///DCCCXCVIII
        ///MMMDCCCCX [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Problem089Data {
            get {
                return ResourceManager.GetString("Problem089Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid 01
        ///003020600
        ///900305001
        ///001806400
        ///008102900
        ///700000008
        ///006708200
        ///002609500
        ///800203009
        ///005010300
        ///Grid 02
        ///200080300
        ///060070084
        ///030500209
        ///000105408
        ///000000000
        ///402706000
        ///301007040
        ///720040060
        ///004010003
        ///Grid 03
        ///000000907
        ///000420180
        ///000705026
        ///100904000
        ///050000040
        ///000507009
        ///920108000
        ///034059000
        ///507000000
        ///Grid 04
        ///030050040
        ///008010500
        ///460000012
        ///070502080
        ///000603000
        ///040109030
        ///250000098
        ///001020600
        ///080060020
        ///Grid 05
        ///020810740
        ///700003100
        ///090002805
        ///009040087
        ///400208003
        ///160030200
        ///30270 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Problem096Data {
            get {
                return ResourceManager.GetString("Problem096Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;A&quot;,&quot;ABILITY&quot;,&quot;ABLE&quot;,&quot;ABOUT&quot;,&quot;ABOVE&quot;,&quot;ABSENCE&quot;,&quot;ABSOLUTELY&quot;,&quot;ACADEMIC&quot;,&quot;ACCEPT&quot;,&quot;ACCESS&quot;,&quot;ACCIDENT&quot;,&quot;ACCOMPANY&quot;,&quot;ACCORDING&quot;,&quot;ACCOUNT&quot;,&quot;ACHIEVE&quot;,&quot;ACHIEVEMENT&quot;,&quot;ACID&quot;,&quot;ACQUIRE&quot;,&quot;ACROSS&quot;,&quot;ACT&quot;,&quot;ACTION&quot;,&quot;ACTIVE&quot;,&quot;ACTIVITY&quot;,&quot;ACTUAL&quot;,&quot;ACTUALLY&quot;,&quot;ADD&quot;,&quot;ADDITION&quot;,&quot;ADDITIONAL&quot;,&quot;ADDRESS&quot;,&quot;ADMINISTRATION&quot;,&quot;ADMIT&quot;,&quot;ADOPT&quot;,&quot;ADULT&quot;,&quot;ADVANCE&quot;,&quot;ADVANTAGE&quot;,&quot;ADVICE&quot;,&quot;ADVISE&quot;,&quot;AFFAIR&quot;,&quot;AFFECT&quot;,&quot;AFFORD&quot;,&quot;AFRAID&quot;,&quot;AFTER&quot;,&quot;AFTERNOON&quot;,&quot;AFTERWARDS&quot;,&quot;AGAIN&quot;,&quot;AGAINST&quot;,&quot;AGE&quot;,&quot;AGENCY&quot;,&quot;AGENT&quot;,&quot;AGO&quot;,&quot;AGREE&quot;,&quot;AGREEMENT&quot;,&quot....
        /// </summary>
        internal static string Problem098Data {
            get {
                return ResourceManager.GetString("Problem098Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 519432,525806
        ///632382,518061
        ///78864,613712
        ///466580,530130
        ///780495,510032
        ///525895,525320
        ///15991,714883
        ///960290,502358
        ///760018,511029
        ///166800,575487
        ///210884,564478
        ///555151,523163
        ///681146,515199
        ///563395,522587
        ///738250,512126
        ///923525,503780
        ///595148,520429
        ///177108,572629
        ///750923,511482
        ///440902,532446
        ///881418,505504
        ///422489,534197
        ///979858,501616
        ///685893,514935
        ///747477,511661
        ///167214,575367
        ///234140,559696
        ///940238,503122
        ///728969,512609
        ///232083,560102
        ///900971,504694
        ///688801,514772
        ///189664,569402
        ///891022,505104
        ///4456 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Problem099Data {
            get {
                return ResourceManager.GetString("Problem099Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -340,495,-153,-910,835,-947
        ///-175,41,-421,-714,574,-645
        ///-547,712,-352,579,951,-786
        ///419,-864,-83,650,-399,171
        ///-429,-89,-357,-930,296,-29
        ///-734,-702,823,-745,-684,-62
        ///-971,762,925,-776,-663,-157
        ///162,570,628,485,-807,-896
        ///641,91,-65,700,887,759
        ///215,-496,46,-931,422,-30
        ///-119,359,668,-609,-358,-494
        ///440,929,968,214,760,-857
        ///-700,785,838,29,-216,411
        ///-770,-458,-325,-53,-505,633
        ///-752,-805,349,776,-799,687
        ///323,5,561,-36,919,-560
        ///-907,358,264,320,204,274
        ///-728,-466,350,969,292,-345
        ///940,836,272,-533,748, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Problem102Data {
            get {
                return ResourceManager.GetString("Problem102Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 81,88,75,42,87,84,86,65
        ///157,150,164,119,79,159,161,139,158
        ///673,465,569,603,629,592,584,300,601,599,600
        ///90,85,83,84,65,87,76,46
        ///165,168,169,190,162,85,176,167,127
        ///224,275,278,249,277,279,289,295,139
        ///354,370,362,384,359,324,360,180,350,270
        ///599,595,557,298,448,596,577,667,597,588,602
        ///175,199,137,88,187,173,168,171,174
        ///93,187,196,144,185,178,186,202,182
        ///157,155,81,158,119,176,152,167,159
        ///184,165,159,166,163,167,174,124,83
        ///1211,1212,1287,605,1208,1189,1060,1216,1243,1200,908,1210
        ///339,299,153,305,282 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Problem105Data {
            get {
                return ResourceManager.GetString("Problem105Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -,-,-,427,668,495,377,678,-,177,-,-,870,-,869,624,300,609,131,-,251,-,-,-,856,221,514,-,591,762,182,56,-,884,412,273,636,-,-,774
        ///-,-,262,-,-,508,472,799,-,956,578,363,940,143,-,162,122,910,-,729,802,941,922,573,531,539,667,607,-,920,-,-,315,649,937,-,185,102,636,289
        ///-,262,-,-,926,-,958,158,647,47,621,264,81,-,402,813,649,386,252,391,264,637,349,-,-,-,108,-,727,225,578,699,-,898,294,-,575,168,432,833
        ///427,-,-,-,366,-,-,635,-,32,962,468,893,854,718,427,448,916,258,-,760,909,529,311,404,-,-,588,680,875,-,615 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Problem107Data {
            get {
                return ResourceManager.GetString("Problem107Data", resourceCulture);
            }
        }
    }
}
